<a href="https://colab.research.google.com/github/iampundir/Psycho-graphic-Segmentation-on-campaign-data/blob/master/Psycho_graphic_Segmentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
files.upload()

Saving psychographic_data.csv to psychographic_data.csv

{'psychographic_data.csv': b'Srl No.,I generally plan my expenses and never spend more than my budget ,I often take opinions or check reviews before buying,I often experiment with new brands rather than just sticking to old ones ,I like to spend my weekends with friends than staying at home . ,My favorite subjects in school were Mathematics & Science rather than Literature,"I make it a point to do some physical exercises (like swimming, walking, yoga) almost everyday","When I go out for shopping, I end up buying more items just by impulse",I am active on almost all Social media  ,"I like light, sober colors to bright, exciting colors when it comes to clothing ",I prefer watching videos/shows online rather than watching them in the television,I prefer ordering in from online apps than dining out,"I follow Brands, celebrities, influencers on social media",I always try to keep up with new fashion trends,I prefer reading or listening to music rather than exercising or playing a sport,Which company\'s mobile phone do you use ?,From where did you purchase your phone?,Which flavor of soft drink do you like to have the most ?,Given below is a list of products. Please tell us how frequently do you use these products  [Shower gels],Given below is a list of products. Please tell us how frequently do you use these products  [Hand sanitizers],Given below is a list of products. Please tell us how frequently do you use these products  [Facewashes],Given below is a list of products. Please tell us how frequently do you use these products  [Hair Conditioner],I generally read news from,I generally prefer to buy clothes from,Age ,Gender,Your hometown ?,Occupation \r\n1,6,9,9,3,10,8,6,7,10,8,1,0,3,9,Apple,Retail,I do not consume soft drinks at all,Less Often,Never,Less Often,Less Often,Newspaper,Retail Stores,40-50,Male,Kolkata,Self Employed/business\r\n2,2,8,5,8,1,0,10,9,7,10,5,7,0,10,One Plus,Online,Cola,Everyday,Less Often,Everyday,Never,Online,Retail Stores,24-28,Female,Other towns in East,Student\r\n3,5,10,5,7,10,6,10,4,10,10,5,0,0,5,Xiaomi,Online,Cola,Everyday,Everyday,Everyday,Never,Online,Retail Stores,24-28,Male,Delhi,Student\r\n4,3,8,7,8,5,3,5,0,9,8,1,6,4,7,Samsung,Retail,Fruit flavour,Less Often,Never,Everyday,Less Often,Online,Online,24-28,Male,Kolkata,Student\r\n5,9,10,8,5,9,7,0,4,10,10,8,6,7,3,Xiaomi,Online,Cola,Less Often,Less Often,Everyday,Never,Online,Online,18-23,Male,Other towns in North,Student\r\n6,7,8,4,5,10,1,5,4,7,8,3,3,0,8,Xiaomi,Online,Orange,Never,Less Often,Never,Never,Online,Online,24-28,Male,Other towns in East,Student\r\n7,2,7,5,8,10,4,10,2,7,9,9,4,10,8,Others,Online,Cola,Everyday,Everyday,Everyday,Less Often,Online,Online,24-28,Male,Other towns in East,Student\r\n8,4,9,9,6,4,3,9,10,5,5,5,7,4,9,Xiaomi,Retail,Fruit flavour,Less Often,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Male,Bangalore,Student\r\n9,7,5,3,2,1,0,3,6,5,7,2,1,8,9,Samsung,Retail,Cola,Never,Never,Everyday,Everyday,Online,Retail Stores,18-23,Female,Mumbai,Student\r\n10,5,9,3,3,10,1,8,5,2,7,8,2,5,8,Xiaomi,Online,Cola,Less Often,Everyday,Everyday,Less Often,Online,Retail Stores,24-28,Male,Mumbai,Student\r\n11,6,6,5,6,6,3,1,5,5,5,5,2,5,5,Others,Retail,Cola,Never,Less Often,Everyday,Never,Online,Retail Stores,24-28,Male,Other towns in West,Student\r\n12,8,7,8,4,10,6,3,7,2,5,2,1,8,4,One Plus,Online,Cola,Never,Never,Less Often,Never,Newspaper,Retail Stores,24-28,Male,Other towns in West,Student\r\n13,8,8,7,2,8,8,2,2,8,7,8,3,2,0,Xiaomi,Online,I do not consume soft drinks at all,Never,Never,Never,Never,Newspaper,Online,24-28,Male,Mumbai,Student\r\n14,3,5,4,5,1,9,7,8,8,10,3,8,5,2,One Plus,Online,Cola,Everyday,Less Often,Everyday,Less Often,Online,Online,24-28,Female,Other towns in West,Student\r\n15,2,4,9,7,5,1,10,8,6,10,0,7,10,10,One Plus,Online,Cola,Never,Less Often,Everyday,Everyday,Online,Retail Stores,18-23,Female,Other towns in West,Student\r\n16,9,8,7,6,8,3,8,8,8,9,2,7,3,6,Others,Online,White/Colourless,Everyday,Less Often,Everyday,Less Often,Online,Retail Stores,18-23,Female,Kolkata,Student\r\n17,4,8,8,5,2,4,0,0,6,8,8,0,4,5,Xiaomi,Online,Cola,Never,Everyday,Less Often,Never,Online,Online,24-28,Male,Kolkata,Student\r\n18,8,6,3,8,9,9,10,10,7,3,3,4,8,2,Apple,Retail,Cola,Less Often,Everyday,Everyday,Less Often,Online,Retail Stores,24-28,Male,Delhi,Student\r\n19,8,8,5,3,7,4,5,2,8,7,3,2,4,8,Others,Online,White/Colourless,Never,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Female,Other towns in West,Student\r\n20,4,3,6,4,4,0,8,3,7,8,3,2,2,5,Vivo,Retail,White/Colourless,Less Often,Less Often,Never,Less Often,Online,Retail Stores,24-28,Female,Other towns in South,Student\r\n21,6,9,5,7,8,1,7,8,3,8,3,8,2,5,One Plus,Online,Cola,Never,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in South,Student\r\n22,8,8,10,8,5,3,7,10,10,10,7,10,10,5,One Plus,Online,White/Colourless,Everyday,Everyday,Everyday,Everyday,Online,Retail Stores,18-23,Female,Mumbai,Student\r\n23,3,6,6,7,6,2,7,8,5,5,4,7,7,7,Vivo,Online,Cola,Never,Less Often,Everyday,Less Often,Online,Online,18-23,Female,Other towns in North,Student\r\n24,7,8,5,4,9,2,7,5,7,9,3,6,6,7,Xiaomi,Online,Orange,Less Often,Less Often,Everyday,Less Often,Online,Retail Stores,18-23,Female,Other towns in North,Student\r\n25,3,9,7,8,7,3,7,7,8,8,6,6,6,9,Apple,Retail,Cola,Less Often,Never,Less Often,Less Often,Online,Retail Stores,24-28,Male,Other towns in North,Student\r\n26,1,4,5,3,5,2,9,6,3,10,5,9,7,6,Apple,Online,I do not consume soft drinks at all,Less Often,Everyday,Everyday,Less Often,Online,Retail Stores,24-28,Female,Mumbai,Student\r\n27,7,8,6,5,5,6,7,5,4,9,7,6,9,4,One Plus,Online,Fruit flavour,Less Often,Everyday,Everyday,Never,Online,Retail Stores,29-33,Male,Delhi,Student\r\n28,9,7,9,6,8,7,4,3,5,6,2,2,9,4,Xiaomi,Online,Fruit flavour,Everyday,Less Often,Everyday,Everyday,Newspaper,Retail Stores,18-23,Female,Delhi,Student\r\n29,5,7,6,5,9,6,3,4,8,8,5,6,6,5,Xiaomi,Online,Cola,Never,Everyday,Everyday,Everyday,Online,Retail Stores,24-28,Female,Other towns in West,Student\r\n30,4,6,8,5,1,1,8,6,1,9,5,0,1,8,Oppo,Retail,Cola,Everyday,Less Often,Less Often,Less Often,Online,Online,18-23,Female,Mumbai,Student\r\n31,1,8,4,3,9,2,8,1,5,9,2,2,6,6,One Plus,Online,Cola,Less Often,Never,Everyday,Less Often,Online,Online,24-28,Female,Kolkata,Student\r\n32,8,5,5,5,7,3,8,7,9,9,8,2,2,10,Apple,Retail,Cola,Everyday,Less Often,Everyday,Less Often,Online,Online,24-28,Female,Mumbai,Student\r\n33,9,9,9,5,9,6,7,4,7,9,9,6,8,6,Xiaomi,Online,White/Colourless,Less Often,Less Often,Less Often,Never,Online,Online,24-28,Female,Other towns in West,Student\r\n34,8,8,6,9,2,10,3,6,7,9,3,3,7,4,Xiaomi,Online,White/Colourless,Everyday,Never,Everyday,Less Often,Online,Retail Stores,24-28,Male,Delhi,Student\r\n35,7,8,9,10,10,7,8,7,5,9,4,5,9,5,One Plus,Online,Cola,Never,Never,Everyday,Less Often,Newspaper,Online,18-23,Male,Other towns in West,Student\r\n36,1,10,6,10,10,6,10,6,10,5,4,5,10,1,Apple,Online,Fruit flavour,Everyday,Never,Everyday,Everyday,Online,Online,24-28,Male,Other towns in North,Student\r\n37,7,10,1,8,5,7,4,8,7,8,3,5,8,2,Oppo,Retail,Cola,Less Often,Everyday,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in East,Student\r\n38,3,9,6,4,9,0,9,4,5,10,3,8,3,10,Apple,Online,Cola,Less Often,Less Often,Everyday,Less Often,Online,Online,24-28,Male,Delhi,Student\r\n39,1,4,5,1,9,4,5,6,2,9,4,1,2,5,Others,Online,Orange,Never,Less Often,Everyday,Never,Online,Online,24-28,Male,Other towns in West,Student\r\n40,8,2,8,8,5,0,8,6,10,10,3,7,10,9,Apple,Online,Orange,Everyday,Everyday,Everyday,Less Often,Online,Online,18-23,Female,Other towns in West,Student\r\n41,8,9,9,5,10,4,8,6,9,10,4,7,4,3,One Plus,Online,White/Colourless,Never,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in South,Student\r\n42,4,2,4,5,5,4,2,6,8,3,6,3,2,8,Others,Online,White/Colourless,Less Often,Less Often,Everyday,Less Often,Online,Online,24-28,Female,Other towns in South,Student\r\n43,7,9,5,5,5,4,4,3,5,5,3,2,0,4,Others,Online,Cola,Never,Everyday,Less Often,Less Often,Online,Retail Stores,24-28,Male,Delhi,Student\r\n44,4,9,9,9,9,1,7,3,8,9,9,8,9,9,Apple,Online,Cola,Less Often,Everyday,Everyday,Everyday,Newspaper,Retail Stores,24-28,Male,Delhi,Student\r\n45,7,9,8,5,5,2,6,6,4,8,2,3,1,10,Xiaomi,Online,Fruit flavour,Never,Everyday,Less Often,Less Often,Online,Retail Stores,24-28,Male,Other towns in South,Student\r\n46,8,6,8,9,7,7,6,6,6,6,6,6,6,5,One Plus,Online,Cola,Less Often,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in West,Student\r\n47,8,10,8,8,8,6,3,0,5,8,8,3,5,7,Others,Online,Cola,Less Often,Never,Everyday,Never,Online,Online,24-28,Male,Kolkata,Student\r\n48,7,9,6,5,3,7,2,7,10,10,3,3,6,3,One Plus,Online,Cola,Less Often,Less Often,Everyday,Everyday,Online,Retail Stores,24-28,Female,Mumbai,Student\r\n49,3,8,6,1,1,5,8,7,7,5,8,6,3,8,Xiaomi,Online,I do not consume soft drinks at all,Everyday,Less Often,Everyday,Less Often,Online,Online,24-28,Female,Delhi,Student\r\n50,3,7,7,6,8,10,8,1,7,9,8,8,7,0,Others,Online,Fruit flavour,Never,Never,Everyday,Less Often,Online,Online,24-28,Female,Other towns in West,Student\r\n51,1,9,7,2,5,0,10,1,10,10,5,10,9,3,One Plus,Retail,Cola,Never,Never,Everyday,Never,Online,Retail Stores,18-23,Male,Chennai,Student\r\n52,4,8,8,7,10,5,10,9,0,7,5,7,9,0,Apple,Retail,Fruit flavour,Everyday,Less Often,Everyday,Less Often,Online,Retail Stores,18-23,Male,Delhi,Student\r\n53,7,8,6,5,4,0,1,4,3,5,1,1,3,9,One Plus,Online,Orange,Everyday,Everyday,Everyday,Less Often,Online,Retail Stores,24-28,Female,Kolkata,Student\r\n54,6,5,4,4,6,1,8,5,6,4,5,4,7,5,Apple,Retail,Cola,Less Often,Everyday,Everyday,Less Often,Online,Retail Stores,18-23,Female,Delhi,Student\r\n55,6,6,6,7,8,7,7,3,7,8,5,4,3,5,Apple,Online,Orange,Everyday,Less Often,Everyday,Never,Online,Retail Stores,24-28,Male,Other towns in North,Student\r\n56,9,8,7,4,5,2,4,4,6,8,4,3,3,5,Others,Online,White/Colourless,Less Often,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Male,Bangalore,Student\r\n57,7,9,3,4,8,4,7,7,8,8,7,6,4,5,Apple,Online,Fruit flavour,Less Often,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Female,Mumbai,Student\r\n58,7,8,6,3,8,2,4,6,4,8,4,9,3,9,Xiaomi,Online,Orange,Never,Less Often,Less Often,Never,Online,Retail Stores,18-23,Male,Other towns in West,Student\r\n59,10,5,10,5,0,0,6,5,10,5,5,0,7,4,Apple,Retail,White/Colourless,Everyday,Less Often,Everyday,Less Often,Online,Online,24-28,Male,Delhi,Self Employed/business\r\n60,4,9,6,5,6,3,6,8,7,7,9,9,3,8,Xiaomi,Online,Cola,Less Often,Everyday,Everyday,Less Often,Online,Online,24-28,Male,Other towns in East,Student\r\n61,4,8,6,10,10,5,3,7,2,2,2,6,7,8,Xiaomi,Online,White/Colourless,Less Often,Everyday,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in South,Student\r\n62,4,10,8,5,3,3,8,3,10,10,10,3,9,10,One Plus,Online,Cola,Less Often,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in West,Student\r\n63,4,8,1,5,3,6,8,8,0,7,3,2,6,4,Samsung,Retail,Cola,Less Often,Never,Everyday,Everyday,Online,Retail Stores,24-28,Female,Other towns in North,Student\r\n64,0,10,8,6,0,10,7,8,3,10,10,7,0,5,One Plus,Online,Cola,Everyday,Less Often,Everyday,Less Often,Online,Online,24-28,Male,Other towns in West,Student\r\n65,6,8,5,8,6,8,7,7,6,5,4,7,8,9,Apple,Retail,Cola,Everyday,Less Often,Everyday,Everyday,Online,Retail Stores,18-23,Female,Mumbai,Student\r\n66,7,7,9,6,10,10,9,6,4,10,8,8,7,4,Apple,Online,I do not consume soft drinks at all,Everyday,Less Often,Everyday,Less Often,Online,Online,24-28,Male,Other towns in West,Student\r\n67,7,9,9,7,10,2,2,9,9,5,7,3,5,9,Apple,Retail,Cola,Everyday,Less Often,Everyday,Less Often,Online,Retail Stores,18-23,Female,Other towns in North,Student\r\n68,10,8,5,10,10,4,7,10,10,5,10,2,4,5,Xiaomi,Online,Orange,Less Often,Never,Less Often,Never,Online,Retail Stores,24-28,Male,Mumbai,Student\r\n69,8,9,6,7,3,4,2,4,8,9,8,2,1,10,Samsung,Retail,I do not consume soft drinks at all,Never,Less Often,Everyday,Less Often,Online,Retail Stores,18-23,Male,Other towns in West,Student\r\n70,4,9,8,9,1,3,9,8,5,8,4,7,5,8,Others,Online,Cola,Everyday,Less Often,Less Often,Less Often,Online,Retail Stores,24-28,Female,Mumbai,Student\r\n71,7,9,8,4,7,8,9,9,6,8,5,7,9,4,One Plus,Online,Cola,Less Often,Everyday,Everyday,Less Often,Online,Retail Stores,24-28,Male,Delhi,Student\r\n72,8,9,9,9,8,8,9,8,8,8,8,9,9,7,Xiaomi,Online,Fruit flavour,Everyday,Less Often,Everyday,Everyday,Online,Online,18-23,Male,Other towns in North,Student\r\n73,2,10,4,4,10,6,10,3,0,10,4,10,9,8,Others,Retail,I do not consume soft drinks at all,Everyday,Everyday,Everyday,Less Often,Online,Online,24-28,Female,Delhi,Student\r\n74,2,8,2,9,9,5,2,8,1,9,1,7,4,3,One Plus,Online,Fruit flavour,Less Often,Everyday,Less Often,Less Often,Online,Retail Stores,24-28,Male,Other towns in South,Student\r\n75,4,7,3,5,9,2,3,6,5,8,3,3,1,9,One Plus,Retail,Cola,Less Often,Never,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in West,Student\r\n76,7,9,7,5,8,5,3,8,5,8,5,3,5,5,Apple,Retail,Cola,Everyday,Less Often,Everyday,Less Often,Online,Retail Stores,18-23,Female,Other towns in West,Student\r\n77,5,8,5,7,8,2,4,2,8,8,5,2,4,8,One Plus,Online,White/Colourless,Less Often,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in West,Student\r\n78,10,6,9,3,0,8,2,2,1,10,5,0,5,5,Others,Online,White/Colourless,Everyday,Never,Everyday,Less Often,Online,Online,24-28,Male,Other towns in East,Student\r\n79,5,8,3,3,10,1,6,10,10,7,1,9,10,10,Xiaomi,Online,Cola,Everyday,Everyday,Everyday,Less Often,Online,Online,24-28,Female,Other towns in East,Student\r\n80,2,9,6,7,3,2,9,0,9,9,2,1,6,8,Xiaomi,Online,Orange,Less Often,Less Often,Everyday,Everyday,Online,Retail Stores,24-28,Female,Kolkata,Student\r\n81,10,10,5,8,10,10,0,10,5,5,0,0,0,0,Samsung,Second hand mobile sources,Cola,Never,Never,Less Often,Less Often,Online,Retail Stores,18-23,Female,Other towns in West,Student\r\n82,9,10,9,5,3,3,3,6,8,10,8,8,7,9,One Plus,Online,Cola,Everyday,Less Often,Everyday,Less Often,Online,Retail Stores,18-23,Female,Other towns in East,Student\r\n83,9,9,3,5,4,0,8,3,8,5,5,0,0,5,Xiaomi,Online,White/Colourless,Never,Less Often,Never,Never,Online,Retail Stores,24-28,Male,Kolkata,Student\r\n84,8,9,6,8,10,7,10,2,8,9,2,2,8,5,Samsung,Online,White/Colourless,Less Often,Less Often,Everyday,Never,Newspaper,Retail Stores,24-28,Male,Mumbai,Student\r\n85,10,10,8,8,10,10,7,6,5,10,8,3,5,5,Xiaomi,Online,Cola,Less Often,Everyday,Less Often,Less Often,Online,Retail Stores,24-28,Male,Mumbai,Student\r\n86,4,7,8,9,8,4,8,7,5,8,8,8,7,7,Apple,Retail,Cola,Everyday,Less Often,Everyday,Never,Newspaper,Retail Stores,18-23,Male,Other towns in South,Student\r\n87,3,9,2,10,3,9,10,8,1,9,0,1,1,2,Xiaomi,Online,I do not consume soft drinks at all,Never,Everyday,Everyday,Everyday,Online,Retail Stores,18-23,Female,Other towns in West,Student\r\n88,8,10,9,7,7,8,3,9,9,10,4,6,6,7,Others,Online,Cola,Everyday,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in West,Student\r\n89,5,4,10,10,0,9,6,10,0,10,0,10,10,0,Apple,Online,Cola,Everyday,Everyday,Everyday,Everyday,Online,Online,24-28,Male,Delhi,Student\r\n90,6,9,10,3,5,8,7,0,3,10,6,7,3,7,Apple,Online,Cola,Less Often,Less Often,Everyday,Less Often,Online,Online,24-28,Male,Other towns in West,Student\r\n91,8,8,4,7,7,3,1,4,1,8,2,6,6,9,Xiaomi,Online,Cola,Never,Less Often,Everyday,Less Often,Online,Retail Stores,18-23,Female,Other towns in West,Student\r\n92,4,9,7,7,2,6,9,4,8,8,2,8,7,2,Xiaomi,Online,I do not consume soft drinks at all,Everyday,Less Often,Everyday,Never,Online,Retail Stores,18-23,Female,Kolkata,Student\r\n93,5,5,7,9,9,5,2,5,9,6,1,4,9,2,Apple,Retail,Cola,Never,Never,Everyday,Never,Online,Retail Stores,24-28,Male,Other towns in North,Student\r\n94,7,7,9,7,10,7,8,4,2,9,6,5,8,0,Others,Online,Fruit flavour,Less Often,Everyday,Everyday,Less Often,Online,Online,24-28,Male,Other towns in North,Student\r\n95,3,7,7,8,7,2,0,0,8,10,2,7,0,10,Others,Online,Orange,Less Often,Never,Less Often,Less Often,Online,Online,24-28,Male,Other towns in North,Student\r\n96,1,8,2,9,10,1,6,7,7,9,5,4,7,7,Others,Online,Fruit flavour,Less Often,Never,Everyday,Less Often,Online,Retail Stores,18-23,Male,Other towns in West,Student\r\n97,5,7,7,5,5,8,7,0,8,5,2,1,4,0,Others,Retail,I do not consume soft drinks at all,Never,Less Often,Everyday,Everyday,Newspaper,Retail Stores,24-28,Female,Mumbai,Student\r\n98,5,7,9,8,10,3,7,8,1,0,2,8,8,8,One Plus,Online,Fruit flavour,Less Often,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in West,Student\r\n99,3,4,4,7,9,2,9,9,2,8,3,8,9,9,Apple,Online,Orange,Everyday,Everyday,Everyday,Everyday,Online,Retail Stores,24-28,Female,Other towns in West,Student\r\n100,4,3,6,0,1,0,4,7,9,3,2,7,8,10,Xiaomi,Online,I do not consume soft drinks at all,Never,Less Often,Everyday,Everyday,Online,Retail Stores,18-23,Female,Mumbai,Student\r\n101,4,9,3,0,8,0,7,5,9,9,0,2,1,5,Xiaomi,Online,I do not consume soft drinks at all,Everyday,Never,Everyday,Never,Newspaper,Retail Stores,18-23,Female,Other towns in South,Student\r\n102,5,3,9,10,10,10,6,8,5,6,3,4,7,1,Others,Retail,Fruit flavour,Less Often,Less Often,Everyday,Never,Online,Retail Stores,18-23,Male,Hyderabad,Student\r\n103,8,9,4,4,5,6,2,8,8,8,5,6,3,4,Xiaomi,Online,Cola,Less Often,Everyday,Less Often,Less Often,Online,Retail Stores,24-28,Male,Chennai,Student\r\n104,4,7,5,6,9,4,7,4,8,8,3,7,4,7,Others,Online,Cola,Less Often,Less Often,Everyday,Less Often,Online,Retail Stores,18-23,Female,Other towns in North,Student\r\n105,8,9,7,5,9,5,6,3,1,7,2,8,7,1,Xiaomi,Online,White/Colourless,Never,Less Often,Everyday,Less Often,Newspaper,Online,24-28,Male,Other towns in West,Student\r\n106,8,8,6,7,3,5,3,5,9,9,5,8,5,7,Samsung,Online,I do not consume soft drinks at all,Everyday,Never,Everyday,Never,Online,Retail Stores,24-28,Female,Other towns in North,Student\r\n107,4,8,5,8,9,3,5,2,9,8,3,10,7,9,Apple,Online,Cola,Everyday,Less Often,Everyday,Everyday,Online,Retail Stores,24-28,Female,Other towns in East,Student\r\n108,6,7,4,6,10,1,6,5,5,10,4,5,5,7,Apple,Online,White/Colourless,Everyday,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in East,Student\r\n109,3,7,2,6,9,6,5,8,7,7,4,6,7,6,Xiaomi,Online,White/Colourless,Less Often,Less Often,Never,Less Often,Online,Online,24-28,Male,Other towns in East,Student\r\n110,6,10,4,2,3,1,9,1,10,6,5,8,6,10,Others,Online,Cola,Everyday,Less Often,Everyday,Everyday,Online,Online,24-28,Female,Other towns in West,Student\r\n111,2,6,1,5,7,2,1,3,9,8,2,8,5,9,Apple,Online,Fruit flavour,Less Often,Less Often,Less Often,Less Often,Online,Retail Stores,18-23,Female,Other towns in North,Student\r\n112,1,8,5,2,1,3,1,2,9,7,2,7,2,3,Xiaomi,Online,Orange,Less Often,Never,Everyday,Everyday,Online,Retail Stores,18-23,Female,Kolkata,Student\r\n113,7,9,7,6,8,3,6,3,6,6,5,4,3,6,Others,Online,Cola,Less Often,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in North,Student\r\n114,8,8,8,8,10,10,7,2,4,9,2,3,3,5,Samsung,Retail,Cola,Less Often,Never,Never,Never,Newspaper,Retail Stores,18-23,Male,Kolkata,Student\r\n115,4,7,9,2,2,8,10,8,6,5,2,10,10,5,One Plus,Online,Cola,Never,Less Often,Less Often,Everyday,Online,Retail Stores,18-23,Female,Other towns in South,Student\r\n116,3,9,5,2,8,4,9,1,5,7,6,3,0,10,Others,Online,I do not consume soft drinks at all,Never,Everyday,Everyday,Everyday,Online,Online,18-23,Male,Hyderabad,Student\r\n117,9,8,4,6,9,6,0,6,8,8,5,6,6,3,Others,Retail,Cola,Never,Less Often,Everyday,Less Often,Online,Retail Stores,24-28,Male,Other towns in West,Student\r\n118,4,10,7,8,4,4,8,5,4,8,5,6,3,7,Xiaomi,Online,Fruit flavour,Everyday,Less Often,Less Often,Never,Online,Online,24-28,Male,Other towns in North,Student\r\n119,1,2,2,5,9,4,9,3,5,5,2,0,10,9,Others,Online,Fruit flavour,Everyday,Everyday,Everyday,Less Often,Online,Retail Stores,24-28,Female,Other towns in North,Student\r\n120,9,9,9,9,10,8,9,9,8,8,8,9,8,7,Xiaomi,Online,I do not consume soft drinks at all,Less Often,Less Often,Everyday,

In [ ]:
!ls

In [ ]:
import pandas as pd
psycho_df=pd.read_csv('psychographic_data.csv')
psycho_df.head()

   Srl No.  ...             Occupation
0        1  ...  Self Employed/business
1        2  ...                 Student
2        3  ...                 Student
3        4  ...                 Student
4        5  ...                 Student

[5 rows x 28 columns]

In [ ]:
X=psycho_df.loc[:,'I generally plan my expenses and never spend more than my budget ':'I prefer reading or listening to music rather than exercising or playing a sport']

In [ ]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=4, random_state=123)

kmeans.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=4, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=123, tol=0.0001, verbose=0)

In [ ]:
centroids = pd.DataFrame(kmeans.cluster_centers_, columns=X.columns)

In [ ]:
X["cluster_id"] = kmeans.labels_

In [ ]:
d = centroids.T

In [ ]:
d.to_csv('output.csv', encoding='utf-8', header='true')

In [ ]:
d

                                                           0  ...         3
I generally plan my expenses and never spend mo...  5.356863  ...  6.271318
I often take opinions or check reviews before b...  7.403922  ...  7.418605
I often experiment with new brands rather than ...  5.541176  ...  5.790698
I like to spend my weekends with friends than s...  4.941176  ...  6.507752
My favorite subjects in school were Mathematics...  7.203922  ...  6.275194
I make it a point to do some physical exercises...  3.090196  ...  7.965116
When I go out for shopping, I end up buying mor...  5.388235  ...  4.236434
I am active on almost all Social media              3.176471  ...  4.914729
I like light, sober colors to bright, exciting ...  5.925490  ...  5.368217
I prefer watching videos/shows online rather th...  7.192157  ...  7.589147
I prefer ordering in from online apps than dini...  4.180392  ...  3.635659
I follow Brands, celebrities, influencers on so...  2.929412  ...  4.325581
I always try to keep up with new fashion trends     3.592157  ...  5.767442
I prefer reading or listening to music rather t...  6.866667  ...  2.503876

[14 rows x 4 columns]

In [ ]:
X.cluster_id.value_counts()

2    310
3    258
0    255
1    177
Name: cluster_id, dtype: int64

In [ ]:
psycho_df["cluster_id"] = kmeans.labels_

In [ ]:
psycho_df[psycho_df['cluster_id']==0].head()

   Srl No.  ...  cluster_id
0        1  ...           0
2        3  ...           0
3        4  ...           0
5        6  ...           0
8        9  ...           0

[5 rows x 29 columns]

In [ ]:
psycho_df.columns

Index(['Srl No.',
       'I generally plan my expenses and never spend more than my budget ',
       'I often take opinions or check reviews before buying',
       'I often experiment with new brands rather than just sticking to old ones ',
       'I like to spend my weekends with friends than staying at home . ',
       'My favorite subjects in school were Mathematics & Science rather than Literature',
       'I make it a point to do some physical exercises (like swimming, walking, yoga) almost everyday',
       'When I go out for shopping, I end up buying more items just by impulse',
       'I am active on almost all Social media  ',
       'I like light, sober colors to bright, exciting colors when it comes to clothing ',
       'I prefer watching videos/shows online rather than watching them in the television',
       'I prefer ordering in from online apps than dining out',
       'I follow Brands, celebrities, influencers on social media',
       'I always try to keep up with new fashion trends',
       'I prefer reading or listening to music rather than exercising or playing a sport',
       'Which companys mobile phone do you use',
       'From where did you purchase your phone?',
       'Which flavor of soft drink do you like to have the most ?',
       'Given below is a list of products. Please tell us how frequently do you use these products  [Shower gels]',
       'Given below is a list of products. Please tell us how frequently do you use these products  [Hand sanitizers]',
       'Given below is a list of products. Please tell us how frequently do you use these products  [Facewashes]',
       'Given below is a list of products. Please tell us how frequently do you use these products  [Hair Conditioner]',
       'I generally read news from', 'I generally prefer to buy clothes from',
       'Age ', 'Gender', 'Your hometown ?', 'Occupation ', 'cluster_id'],
      dtype='object')

In [ ]:
psycho_df.rename(columns={"Which company's mobile phone do you use ?": 'Which companys mobile phone do you use'}, inplace=True)

In [ ]:
psycho_df['cluster_id'] = psycho_df['cluster_id'].apply(lambda x: 'OldSchool' if x==0 else x)
psycho_df['cluster_id'] = psycho_df['cluster_id'].apply(lambda x: 'Introvert' if x==1 else x)
psycho_df['cluster_id'] = psycho_df['cluster_id'].apply(lambda x: 'Fashionable' if x==2 else x)
psycho_df['cluster_id'] = psycho_df['cluster_id'].apply(lambda x: 'Pragmatic' if x==3 else x)

In [ ]:
psycho_df.groupby(['Which companys mobile phone do you use','cluster_id'])['cluster_id'].count()

Which companys mobile phone do you use  cluster_id
Apple                                   Fashionable     68
                                        Introvert       39
                                        OldSchool       38
                                        Pragmatic       47
One Plus                                Fashionable     67
                                        Introvert       43
                                        OldSchool       39
                                        Pragmatic       35
Oppo                                    Introvert        3
                                        OldSchool        7
                                        Pragmatic        7
Others                                  Fashionable     43
                                        Introvert       25
                                        OldSchool       65
                                        Pragmatic       66
Samsung                                 Fashionable     10
                                        Introvert       16
                                        OldSchool       25
                                        Pragmatic       15
Vivo                                    Fashionable     10
                                        Introvert        4
                                        OldSchool        7
                                        Pragmatic        8
Xiaomi                                  Fashionable    112
                                        Introvert       47
                                        OldSchool       74
                                        Pragmatic       80
Name: cluster_id, dtype: int64

In [ ]:
psycho_df.groupby(['From where did you purchase your phone?','cluster_id'])['cluster_id'].count()

From where did you purchase your phone?  cluster_id
Online                                   Fashionable    251
                                         Introvert      125
                                         OldSchool      192
                                         Pragmatic      181
Retail                                   Fashionable     59
                                         Introvert       48
                                         OldSchool       63
                                         Pragmatic       66
Second hand mobile sources               Introvert        4
                                         Pragmatic       11
Name: cluster_id, dtype: int64

In [ ]:
psycho_df.groupby(['Age ','cluster_id','Which companys mobile phone do you use'])['cluster_id'].count()

Age    cluster_id   Which companys mobile phone do you use
18-23  Fashionable  Apple                                     29
                    One Plus                                  31
                    Others                                    11
                    Samsung                                    4
                    Vivo                                       8
                    Xiaomi                                    36
       Introvert    Apple                                      7
                    One Plus                                  28
                    Oppo                                       3
                    Others                                     3
                    Samsung                                    6
                    Xiaomi                                    23
       OldSchool    Apple                                      7
                    One Plus                                  16
                    Oppo                                       3
                    Others                                     6
                    Samsung                                   23
                    Xiaomi                                    21
       Pragmatic    Apple                                     25
                    One Plus                                   3
                    Others                                    23
                    Samsung                                    7
                    Vivo                                       4
                    Xiaomi                                    38
24-28  Fashionable  Apple                                     39
                    One Plus                                  36
                    Others                                    32
                    Samsung                                    6
                    Vivo                                       2
                    Xiaomi                                    76
       Introvert    Apple                                     32
                    One Plus                                  15
                    Others                                    22
                    Samsung                                   10
                    Vivo                                       4
                    Xiaomi                                    24
       OldSchool    Apple                                     29
                    One Plus                                  23
                    Oppo                                       4
                    Others                                    59
                    Samsung                                    2
                    Vivo                                       7
                    Xiaomi                                    53
       Pragmatic    Apple                                     22
                    One Plus                                  29
                    Oppo                                       7
                    Others                                    43
                    Samsung                                    8
                    Vivo                                       4
                    Xiaomi                                    42
29-33  Pragmatic    One Plus                                   3
40-50  OldSchool    Apple                                      2
Name: cluster_id, dtype: int64

In [ ]:
pd.crosstab(index=[psycho_df['Age '], psycho_df['cluster_id']], columns=psycho_df['Which companys mobile phone do you use'])

Which companys mobile phone do you use  Apple  One Plus  ...  Vivo  Xiaomi
Age   cluster_id                                         ...
18-23 Fashionable                          29        31  ...     8      36
      Introvert                             7        28  ...     0      23
      OldSchool                             7        16  ...     0      21
      Pragmatic                            25         3  ...     4      38
24-28 Fashionable                          39        36  ...     2      76
      Introvert                            32        15  ...     4      24
      OldSchool                            29        23  ...     7      53
      Pragmatic                            22        29  ...     4      42
29-33 Pragmatic                             0         3  ...     0       0
40-50 OldSchool                             2         0  ...     0       0

[10 rows x 7 columns]

In [ ]:
pd.crosstab(index=[psycho_df['Age '], psycho_df['cluster_id']], columns=psycho_df['Which flavor of soft drink do you like to have the most ?'])

Which flavor of soft drink do you like to have the most ?  Cola  ...  White/Colourless
Age   cluster_id                                                 ...
18-23 Fashionable                                            73  ...                17
      Introvert                                              33  ...                 5
      OldSchool                                              23  ...                11
      Pragmatic                                              43  ...                12
24-28 Fashionable                                            88  ...                44
      Introvert                                              53  ...                10
      OldSchool                                              65  ...                41
      Pragmatic                                              69  ...                22
29-33 Pragmatic                                               0  ...                 0
40-50 OldSchool                                               0  ...                 0

[10 rows x 5 columns]

In [ ]:
pd.crosstab(index=[psycho_df['Gender'], psycho_df['cluster_id']], columns=psycho_df['Which companys mobile phone do you use'])

Which companys mobile phone do you use  Apple  One Plus  ...  Vivo  Xiaomi
Gender cluster_id                                        ...
Female Fashionable                         23        16  ...     3      28
       Introvert                           24        25  ...     4      25
       OldSchool                           13        21  ...     7      34
       Pragmatic                           10         6  ...     4      29
Male   Fashionable                         45        51  ...     7      84
       Introvert                           15        18  ...     0      22
       OldSchool                           25        18  ...     0      40
       Pragmatic                           37        29  ...     4      51

[8 rows x 7 columns]

In [ ]:
pd.crosstab(index=[psycho_df['Occupation '], psycho_df['cluster_id']], columns=psycho_df['Which companys mobile phone do you use'])

Which companys mobile phone do you use  Apple  One Plus  ...  Vivo  Xiaomi
Occupation             cluster_id                        ...
Self Employed/business Introvert            3         0  ...     0       0
                       OldSchool            2         0  ...     0       0
Student                Fashionable         64        67  ...    10     112
                       Introvert           36        43  ...     4      47
                       OldSchool           36        39  ...     7      74
                       Pragmatic           47        35  ...     8      80
Working Executive      Fashionable          4         0  ...     0       0
                       Introvert            0         0  ...     0       0
                       Pragmatic            0         0  ...     0       0

[9 rows x 7 columns]

In [ ]:
psycho_df.columns

Index(['Srl No.',
       'I generally plan my expenses and never spend more than my budget ',
       'I often take opinions or check reviews before buying',
       'I often experiment with new brands rather than just sticking to old ones ',
       'I like to spend my weekends with friends than staying at home . ',
       'My favorite subjects in school were Mathematics & Science rather than Literature',
       'I make it a point to do some physical exercises (like swimming, walking, yoga) almost everyday',
       'When I go out for shopping, I end up buying more items just by impulse',
       'I am active on almost all Social media  ',
       'I like light, sober colors to bright, exciting colors when it comes to clothing ',
       'I prefer watching videos/shows online rather than watching them in the television',
       'I prefer ordering in from online apps than dining out',
       'I follow Brands, celebrities, influencers on social media',
       'I always try to keep up with new fashion trends',
       'I prefer reading or listening to music rather than exercising or playing a sport',
       'Which companys mobile phone do you use',
       'From where did you purchase your phone?',
       'Which flavor of soft drink do you like to have the most ?',
       'Given below is a list of products. Please tell us how frequently do you use these products  [Shower gels]',
       'Given below is a list of products. Please tell us how frequently do you use these products  [Hand sanitizers]',
       'Given below is a list of products. Please tell us how frequently do you use these products  [Facewashes]',
       'Given below is a list of products. Please tell us how frequently do you use these products  [Hair Conditioner]',
       'I generally read news from', 'I generally prefer to buy clothes from',
       'Age ', 'Gender', 'Your hometown ?', 'Occupation ', 'cluster_id'],
      dtype='object')

In [ ]:
pd.crosstab(index=[psycho_df['Your hometown ?'], psycho_df['cluster_id']], columns=psycho_df['Which companys mobile phone do you use'])

Which companys mobile phone do you use  Apple  One Plus  ...  Vivo  Xiaomi
Your hometown ?      cluster_id                          ...
Bangalore            Introvert              4         4  ...     0       2
                     OldSchool              0         0  ...     0       0
                     Pragmatic              0         0  ...     0       0
Chennai              Fashionable            0         3  ...     0       0
                     Introvert              0         5  ...     0       0
                     OldSchool              0         4  ...     0       0
                     Pragmatic              3         3  ...     0       4
Delhi                Fashionable           19         7  ...     0       8
                     Introvert              3         0  ...     0      17
                     OldSchool              6         0  ...     0       6
                     Pragmatic              9         3  ...     8      15
Hyderabad            OldSchool              0         2  ...     0       2
                     Pragmatic              4         4  ...     0       0
Kolkata              Fashionable            0         3  ...     0       7
                     Introvert              7        10  ...     0       7
                     OldSchool             10         6  ...     0      23
                     Pragmatic              4         0  ...     0       4
Mumbai               Fashionable           16         3  ...     0      10
                     Introvert              7         0  ...     0       4
                     OldSchool              3         0  ...     0       6
                     Pragmatic              0         3  ...     0       6
Other towns in East  Fashionable            8         4  ...     0      26
                     Introvert              4         5  ...     0       7
                     OldSchool              4         3  ...     0       2
                     Pragmatic             11         4  ...     0       4
Other towns in North Fashionable           13        19  ...     8      17
                     Introvert             11         4  ...     0       4
                     OldSchool             10         4  ...     0       3
                     Pragmatic              6         6  ...     0      19
Other towns in South Fashionable            5        15  ...     2       9
                     Introvert              0         3  ...     0       2
                     OldSchool              2         2  ...     7      11
                     Pragmatic              3         3  ...     0       3
Other towns in West  Fashionable            7        13  ...     0      35
                     Introvert              3        12  ...     4       4
                     OldSchool              3        18  ...     0      21
                     Pragmatic              7         9  ...     0      25

[37 rows x 7 columns]

In [ ]:
pd.crosstab(index=psycho_df['Occupation '] , columns=psycho_df['cluster_id'])

cluster_id              Fashionable  Introvert  OldSchool  Pragmatic
Occupation
Self Employed/business            0          6          2          0
Student                         304        167        253        254
Working Executive                 6          4          0          4

In [ ]:
pd.crosstab(index=psycho_df['Age '] , columns=psycho_df['cluster_id'])

cluster_id  Fashionable  Introvert  OldSchool  Pragmatic
Age
18-23               119         70         76        100
24-28               191        107        177        155
29-33                 0          0          0          3
40-50                 0          0          2          0

In [ ]:
pd.crosstab(index=psycho_df['Gender'] , columns=psycho_df['cluster_id'])

cluster_id  Fashionable  Introvert  OldSchool  Pragmatic
Gender
Female               93        110        112         76
Male                217         67        143        182

In [ ]:
 pd.crosstab(index=psycho_df['Occupation '] , columns=[psycho_df['cluster_id'], psycho_df['Which companys mobile phone do you use']])

cluster_id                             Fashionable           ... Pragmatic
Which companys mobile phone do you use       Apple One Plus  ...      Vivo Xiaomi
Occupation                                                   ...
Self Employed/business                           0        0  ...         0      0
Student                                         64       67  ...         8     80
Working Executive                                4        0  ...         0      0

[3 rows x 27 columns]

In [ ]:
pd.crosstab(index=psycho_df['Age '] , columns=[psycho_df['cluster_id'],psycho_df['Which companys mobile phone do you use']])

cluster_id                             Fashionable           ... Pragmatic
Which companys mobile phone do you use       Apple One Plus  ...      Vivo Xiaomi
Age                                                          ...
18-23                                           29       31  ...         4     38
24-28                                           39       36  ...         4     42
29-33                                            0        0  ...         0      0
40-50                                            0        0  ...         0      0

[4 rows x 27 columns]

In [ ]:
pd.crosstab(index=psycho_df['Gender'] , columns=[psycho_df['cluster_id'], psycho_df['Which companys mobile phone do you use']])

cluster_id                             Fashionable           ... Pragmatic
Which companys mobile phone do you use       Apple One Plus  ...      Vivo Xiaomi
Gender                                                       ...
Female                                          23       16  ...         4     29
Male                                            45       51  ...         4     51

[2 rows x 27 columns]

In [ ]:
pd.crosstab(index=[psycho_df['Your hometown ?'], psycho_df['cluster_id']], columns=psycho_df['Which companys mobile phone do you use'])

Which companys mobile phone do you use  Apple  One Plus  ...  Vivo  Xiaomi
Your hometown ?      cluster_id                          ...
Bangalore            Introvert              4         4  ...     0       2
                     OldSchool              0         0  ...     0       0
                     Pragmatic              0         0  ...     0       0
Chennai              Fashionable            0         3  ...     0       0
                     Introvert              0         5  ...     0       0
                     OldSchool              0         4  ...     0       0
                     Pragmatic              3         3  ...     0       4
Delhi                Fashionable           19         7  ...     0       8
                     Introvert              3         0  ...     0      17
                     OldSchool              6         0  ...     0       6
                     Pragmatic              9         3  ...     8      15
Hyderabad            OldSchool              0         2  ...     0       2
                     Pragmatic              4         4  ...     0       0
Kolkata              Fashionable            0         3  ...     0       7
                     Introvert              7        10  ...     0       7
                     OldSchool             10         6  ...     0      23
                     Pragmatic              4         0  ...     0       4
Mumbai               Fashionable           16         3  ...     0      10
                     Introvert              7         0  ...     0       4
                     OldSchool              3         0  ...     0       6
                     Pragmatic              0         3  ...     0       6
Other towns in East  Fashionable            8         4  ...     0      26
                     Introvert              4         5  ...     0       7
                     OldSchool              4         3  ...     0       2
                     Pragmatic             11         4  ...     0       4
Other towns in North Fashionable           13        19  ...     8      17
                     Introvert             11         4  ...     0       4
                     OldSchool             10         4  ...     0       3
                     Pragmatic              6         6  ...     0      19
Other towns in South Fashionable            5        15  ...     2       9
                     Introvert              0         3  ...     0       2
                     OldSchool              2         2  ...     7      11
                     Pragmatic              3         3  ...     0       3
Other towns in West  Fashionable            7        13  ...     0      35
                     Introvert              3        12  ...     4       4
                     OldSchool              3        18  ...     0      21
                     Pragmatic              7         9  ...     0      25

[37 rows x 7 columns]

In [ ]:
pd.crosstab(index=[psycho_df['Your hometown ?'], psycho_df['cluster_id']], columns=psycho_df['Which flavor of soft drink do you like to have the most ?'])

Which flavor of soft drink do you like to have the most ?  Cola  ...  White/Colourless
Your hometown ?      cluster_id                                  ...
Bangalore            Introvert                                8  ...                 0
                     OldSchool                                0  ...                 3
                     Pragmatic                                0  ...                 0
Chennai              Fashionable                              2  ...                 3
                     Introvert                                5  ...                 0
                     OldSchool                                2  ...                 2
                     Pragmatic                                7  ...                 0
Delhi                Fashionable                             31  ...                 3
                     Introvert                                4  ...                 8
                     OldSchool                               11  ...                 7
                     Pragmatic                               21  ...                11
Hyderabad            OldSchool                                2  ...                 0
                     Pragmatic                                0  ...                 4
Kolkata              Fashionable                              7  ...                 3
                     Introvert                               18  ...                 0
                     OldSchool                               24  ...                 8
                     Pragmatic                                8  ...                 4
Mumbai               Fashionable                              6  ...                 9
                     Introvert                                3  ...                 0
                     OldSchool                               18  ...                 0
                     Pragmatic                                6  ...                 0
Other towns in East  Fashionable                             25  ...                15
                     Introvert                               16  ...                 0
                     OldSchool                                0  ...                 7
                     Pragmatic                                7  ...                 7
Other towns in North Fashionable                             40  ...                 4
                     Introvert                                8  ...                 7
                     OldSchool                               15  ...                 0
                     Pragmatic                               23  ...                 0
Other towns in South Fashionable                             16  ...                10
                     Introvert                                7  ...                 0
                     OldSchool                                4  ...                 8
                     Pragmatic                                0  ...                 0
Other towns in West  Fashionable                             34  ...                14
                     Introvert                               17  ...                 0
                     OldSchool                               12  ...                17
                     Pragmatic                               40  ...                 8

[37 rows x 5 columns]

In [ ]:
pd.crosstab(index=[psycho_df['Gender'], psycho_df['cluster_id']], columns=psycho_df['Which flavor of soft drink do you like to have the most ?'])

Which flavor of soft drink do you like to have the most ?  Cola  ...  White/Colourless
Gender cluster_id                                                ...
Female Fashionable                                           43  ...                23
       Introvert                                             49  ...                 7
       OldSchool                                             35  ...                20
       Pragmatic                                             41  ...                12
Male   Fashionable                                          118  ...                38
       Introvert                                             37  ...                 8
       OldSchool                                             53  ...                32
       Pragmatic                                             71  ...                22

[8 rows x 5 columns]

In [ ]:
# take output
#further analysis here : https://docs.google.com/spreadsheets/d/1DKB-iVnEd5eX-Uo2Sk1V6fXE4yguGhnDKK3RJMOjD5E/edit?usp=sharing